server:
  port: 20005

spring:
  application:
    name: todo-kakao
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cew?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      ## sql ???
    properties:
      hibernate.format_sql: false
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      enabled: true

## jwt ?? ?? ? ???? ????
msa:
  jwt:
    secret: abcdefghijklmnopqrstuvwxyz01234567890

oauth:
  kakao:
    client_id: f4112a126c4633ffe4599b9f93cf66dd
    client_secret: PuVcRd78bqSJKDtgQqVDHz96cheimpAj