server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeun0415/spring-cloud-config
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: "*"